name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    if: ${{ contains(join(github.event.commits.*.message, ' '), '#deploy') }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        port: 22
        script: |
          cd ~/projects/shanghai-cardgame
          npm run deploy
    - name: Notification
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://38.242.159.10:2000/'
        method: 'POST'
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"send_main": "New version of Shing Shong is now running"}'
        